### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by aldrichdev** [andreyk1512/react-image-size#1]
I am using `reactImageSize` in a functional component in a Nextjs/TypeScript project like this:

```
import reactImageSize from 'react-image-size'
...
const MyFunctionalComponent = () => {
    const [desktopWidth, setDesktopWidth] = useState(0)
    const [mobileWidth, setMobileWidth] = useState(0)
    const desktopImageUrl = '/img/carousel/collage.png'
    const mobileImageUrl = '/img/carousel/collage-mobile.png'
    
    reactImageSize(desktopImageUrl)
        .then(({ width }) =>  setDesktopWidth(width * 2)) 
        .catch((errorMessage) => console.log(console.error(errorMessage)))

    reactImageSize(mobileImageUrl)
        .then(({ width }) =>  setMobileWidth(width * 2)) 
        .catch((errorMessage) => console.log(console.error(errorMessage)))
        
    ...
}
```

And in Next when I load the page, I get:
![image](https://user-images.githubusercontent.com/17816529/140536369-124cc291-bd2c-4fe2-9046-fe95c921c69f.png)

**Comment by RenatoCesarF** [comment]
I'm having the same issue, did you fixed it?

**Comment by mohsentaleb** [comment]
Having the same using `jest` 👍

**Comment by mednche** [comment]
Having the same issue - any update?

**Comment by andreyk1512** [comment]
Thank you for the report guys.

The bug is fixed in version 1.0.5

**Comment by Frankiz123** [comment]
@andreyk1512  still facing this issue while import in react typescript file

**Comment by andreyk1512** [comment]
@Frankiz123 thank you. It should be fixed in actual version. Please check it.
